services:
  hub:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    # This is the service that hosts the development environment, so we need
    # to keep the container running so that we can work in it. We use the
    # `sleep infinity` command to keep the container running indefinitely.
    command: sleep infinity
    # Ptrace-based debuggers like C++, Go, and Rust require the following.
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
